spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfg_dev
    username: root
    password:
    platform: mysql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: src/main/scripts/database-create.sql
